import Head from "next/head";
import {useState} from "react";

//MUI Imports
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import MyAppBar from "@src/components/common/MyAppBar";
import Link from "next/link"
import {theme} from "../styles/mui/theme";
import {darkTheme} from "../styles/mui/theme";
import { ThemeProvider } from "@emotion/react";

export default function Home(){
  const [visible, setVisible] =  useState(false);    //use camel case

 
  const movies = [
    {
      name: "Avengers",
      img: "https://tse3.mm.bing.net/th/id/OIP.0sL7kz85Olcrwk_GIrClYAHaF7?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
      desc: "Directed by Joss Wheden",
    },

    {
      name: "Terminator",
      img: "https://th.bing.com/th/id/OIP.dGeuxgGzyEvvctdGS1uVZgHaDt?w=282&h=174&c=7&r=0&o=7&cb=ucfimg2&dpr=1.5&pid=1.7&rm=3&ucfimg=1",
      desc: "Directed by James Cameron",
    },
  ];
  return (
    <>
    <ThemeProvider theme={darkTheme}>
      <Head>                   //JSX (JavaScript XML) , ita a component not HTML
        <title>Movie Lovers Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box>
          <Box sx={{ flexGrow: 1 }}>
      <MyAppBar></MyAppBar>
    </Box>
    
    <Button onClick ={() => setVisible(!visible)}>Next</Button>
    <Box height = "200px" />{
      visible?
       (<Box height= "200px" sx={{background: "pink", width:"500px" }} />
       ) : (
       <></>
      )}
    

      </Box>
      </ThemeProvider>
    </>
  );
}
